# -*- coding: utf-8 -*-
"""Kivy_APK_Builder_Colab (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8RvkVWMvDs3Vo6cooobjOnaq_VbnoFU

# 📱 Build a Kivy App into an Android APK in Google Colab
This Colab notebook helps you convert your Kivy `.py` app into an Android APK without needing Android Studio or Linux locally.
"""

# ✅ Step 1: Install buildozer and dependencies
!sudo apt update
!sudo apt install -y zip unzip openjdk-17-jdk python3-pip git
!pip install --upgrade cython virtualenv
!pip install buildozer

# ✅ Step 2: Upload your main.py Kivy file
from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# ✅ Step 3: Setup Buildozer folder and move files
!mkdir -p myapp
# %cd myapp
import shutil, os
for file in uploaded.keys():
    shutil.move(f"../{file}", file)
!buildozer init

# ✅ Step 4: Auto-update the buildozer.spec file
!sed -i 's/^requirements =.*/requirements = python3,kivy/' buildozer.spec
!sed -i 's/^source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
!sed -i 's/^title = .*/title = MyKivyApp/' buildozer.spec
!sed -i 's/^package.name = .*/package.name = mykivyapp/' buildozer.spec
!sed -i 's/^package.domain = .*/package.domain = org.satyamshinde/' buildozer.spec

# ✅ Step 5: Build APK (Takes ~25 mins)
!buildozer -v android debug

"""### 📲 Download your APK
Once the build is complete, your APK file will be located in the sidebar under:
`/content/myapp/bin/`
Right-click → Download the `.apk` file.
"""